joint_state_controller:
  type: 'joint_state_controller/JointStateController'
  publish_rate: 10  

head_servo_velocity_controller:
    type: "velocity_controllers/JointVelocityController"
    joint: head_j
    pid: {p: 100.0, i: 1, d: 10}

neck_servo_velocity_controller:
    type: "velocity_controllers/JointVelocityController"
    joint: neck_j
    pid: {p: 100.0, i: 1, d: 10}
    
hip_r_servo_velocity_controller:
    type: "velocity_controllers/JointVelocityController"
    joint: hip_r_j
    pid: {p: 100.0, i: 1, d: 10}
    
knee_r_servo_velocity_controller:
    type: "velocity_controllers/JointVelocityController"
    joint: knee_r_j
    pid: {p: 100.0, i: 1, d: 10}
    
foot_r_servo_velocity_controller:
    type: "velocity_controllers/JointVelocityController"
    joint: foot_r_j
    pid: {p: 100.0, i: 1, d: 10}
    
hip_l_servo_velocity_controller:
    type: "velocity_controllers/JointVelocityController"
    joint: hip_l_j
    pid: {p: 100.0, i: 1, d: 10}
    
knee_l_servo_velocity_controller:
    type: "velocity_controllers/JointVelocityController"
    joint: knee_l_j
    pid: {p: 100.0, i: 1, d: 10}
    
foot_l_servo_velocity_controller:
    type: "velocity_controllers/JointVelocityController"
    joint: foot_l_j
    pid: {p: 100.0, i: 1, d: 10}


