joint_state_controller:
  type: 'joint_state_controller/JointStateController'
  publish_rate: 50  

head_servo_effort_controller:
    type: "effort_controllers/JointEffortController"
    joint: head_j
    pid: {p: 1.0, i: 0.01, d: 0.1}

neck_servo_effort_controller:
    type: "effort_controllers/JointEffortController"
    joint: neck_j
    pid: {p: 1.0, i: 0.01, d: 0.1}
    
hip_r_servo_effort_controller:
    type: "effort_controllers/JointEffortController"
    joint: up_leg_r_j
    pid: {p: 1.0, i: 0.01, d: 0.1}
    
knee_r_servo_effort_controller:
    type: "effort_controllers/JointEffortController"
    joint: mid_leg_r_j
    pid: {p: 1.0, i: 0.01, d: 0.1}
    
foot_r_servo_effort_controller:
    type: "effort_controllers/JointEffortController"
    joint: feet_r_j
    pid: {p: 1.0, i: 0.01, d: 0.1}
    
hip_l_servo_effort_controller:
    type: "effort_controllers/JointEffortController"
    joint: up_leg_l_j
    pid: {p: 1.0, i: 0.01, d: 0.1}
    
knee_l_servo_effort_controller:
    type: "effort_controllers/JointEffortController"
    joint: mid_leg_l_j
    pid: {p: 1.0, i: 0.01, d: 0.1}
    
foot_l_servo_effort_controller:
    type: "effort_controllers/JointEffortController"
    joint: feet_l_j
    pid: {p: 1.0, i: 0.01, d: 0.1}


