<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="BD1" >
    
    <xacro:include filename="$(find bd1_description)/urdf/bd1_leg.xacro"/>
    <xacro:include filename="$(find bd1_description)/urdf/bd1.gazebo"/>
        
    <xacro:property name="body_aprox_x" value="0.18"/>
    <xacro:property name="body_aprox_y" value="0.12"/>
    <xacro:property name="body_aprox_z" value="0.1"/>
    <xacro:property name="body_mass" value="0.5"/>
    <xacro:property name="body_shift_x" value="-0.015"/>
    <xacro:property name="body_shift_y" value="0.0"/>
    <xacro:property name="body_shift_z" value="0.005"/>
        
    <xacro:property name="neck_mass" value="0.1"/>    
    <xacro:property name="neck_aprox_x" value="0.02"/>
    <xacro:property name="neck_aprox_y" value="0.03"/>
    <xacro:property name="neck_aprox_z" value="0.1"/>
    <xacro:property name="neck_shift_x" value="0.03"/>
    <xacro:property name="neck_shift_y" value="0.0"/>
    <xacro:property name="neck_shift_z" value="0.04"/>
    <xacro:property name="neck_len" value="0.07"/>
    
    <xacro:property name="head_aprox_x" value="0.29"/>
    <xacro:property name="head_aprox_y" value="0.24"/>
    <xacro:property name="head_aprox_z" value="0.08"/>
    <xacro:property name="head_mass" value="0.5"/>    
    <xacro:property name="head_shift_x" value="0.04"/>
    <xacro:property name="head_shift_y" value="0.0"/>
    <xacro:property name="head_shift_z" value="0.07"/>
    <xacro:property name="neck_i_mul" value="10"/>       
    
    
    <xacro:property name="servo_velocity" value="2"/>
    <xacro:property name="servo_friction" value="0.3"/>
    <xacro:property name="servo_effort" value="30"/>
    
    
    <selfCollide>true</selfCollide>
    <!--
        BASE
    -->         
    <link name="base_link">
    </link>                        
    <!--
        BODY
    -->
    <link name="body_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find bd1_description)/mesh/body_m.dae"/> 
                <!--<box size="${body_aprox_x} ${body_aprox_y} ${body_aprox_z}"/>-->
            </geometry>
            <material name="white">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
        
        <collision name="body_link_collision">
            <origin xyz="${body_shift_x} ${body_shift_y} ${body_shift_z}" rpy=" 0 0 0"/>
            <geometry>                                
                <box size="${body_aprox_x} ${body_aprox_y} ${body_aprox_z}"/>
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${body_shift_x} ${body_shift_y} ${body_shift_z}" rpy=" 0 0 0"/>
            <mass value="${body_mass}"/>            
            <inertia
                ixx="${0.08*body_mass*(body_aprox_y*body_aprox_y+body_aprox_z*body_aprox_z)}" ixy="0" ixz="0"
                iyy="${0.08*body_mass*(body_aprox_x*body_aprox_x+body_aprox_z*body_aprox_z)}" iyz="0"
                izz="${0.08*body_mass*(body_aprox_x*body_aprox_x+body_aprox_y*body_aprox_y)}"
            />

        </inertial>
    </link>
    
    <joint name="body_j" type="fixed">
        <parent link="base_link"/>
        <child link="body_link"/>
        
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    
    <!--
        NECK
    -->
    
    <link name="neck_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find bd1_description)/mesh/neck_m.dae"/>     
            </geometry>
        </visual>
        
        <inertial>
            <mass value="${neck_mass}"/>            
            <inertia
                ixx="${neck_i_mul*0.08*neck_mass*(neck_aprox_y*neck_aprox_y+neck_aprox_z*neck_aprox_z)}" ixy="0" ixz="0"
                iyy="${neck_i_mul*0.08*neck_mass*(neck_aprox_x*neck_aprox_x+neck_aprox_z*neck_aprox_z)}" iyz="0"
                izz="${neck_i_mul*0.08*neck_mass*(neck_aprox_x*neck_aprox_x+neck_aprox_y*neck_aprox_y)}"
            />
            <origin xyz="0 0 ${head_shift_z/2}" rpy=" 0 0 0"/>

        </inertial>        
    </link>
    
    <joint name="neck_j" type="revolute">
        <parent link="body_link"/>
        <child link="neck_link"/>
        
        <origin xyz="${neck_shift_x} ${neck_shift_y} ${neck_shift_z}" rpy="0 -1.5 0"/>
        <limit effort="${servo_effort}" velocity="${servo_velocity}" lower="0" upper="${pi}"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="${servo_friction}"/>
    </joint>
    
    <xacro:servtransmission_v joint="neck_j"/>
    
    <!--
        HEAD
    -->
    <link name="head_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find bd1_description)/mesh/head_m.dae"/>                
                <!--<box size="${head_aprox_x} ${head_aprox_y} ${head_aprox_z}"/>-->
            </geometry>            
            <material name="white">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
        
        <collision>
            <origin xyz="${head_shift_x} ${head_shift_y} ${head_shift_z}" rpy=" 0 0 0"/>
            <geometry>                
                <box size="${head_aprox_x} ${head_aprox_y} ${head_aprox_z}"/>
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${head_shift_x} ${head_shift_y} ${head_shift_z}" rpy=" 0 0 0"/>
            <mass value="${head_mass}"/>
            <inertia
                ixx="${0.08*head_mass*(head_aprox_y*head_aprox_y+head_aprox_z*head_aprox_z)}" ixy="0" ixz="0"
                iyy="${0.08*head_mass*(head_aprox_x*head_aprox_x+head_aprox_z*head_aprox_z)}" iyz="0"
                izz="${0.08*head_mass*(head_aprox_x*head_aprox_x+head_aprox_y*head_aprox_y)}"
            />
        </inertial>
    </link>
    
    <joint name="head_j" type="revolute">
        <parent link="neck_link"/>
        <child link="head_link"/>
        
        <origin xyz="0 0 ${neck_len}" rpy="0 1.5 0"/>
        <limit effort="${servo_effort}" velocity="${servo_velocity}" lower="0" upper="${pi}"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="${servo_friction}"/>
    </joint>
    
    <xacro:servtransmission_v joint="head_j"/>
    
    <!--
        LEGS
    -->
    <xacro:bd1_leg side="r" y_mul="-1" servo_velocity="${servo_velocity}" servo_effort="${servo_effort}"/>
    <xacro:bd1_leg side="l" y_mul="1" servo_velocity="${servo_velocity}" servo_effort="${servo_effort}"/>
    
    
    
</robot>
