<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
    
    <xacro:property name="legs_baseline" value="0.12"/>
    
    <xacro:property name="up_leg_aprox_x" value="0.24"/>
    <xacro:property name="up_leg_aprox_y" value="0.04"/>
    <xacro:property name="up_leg_aprox_z" value="0.12"/>
    <xacro:property name="up_leg_mass" value="0.25"/>
    <xacro:property name="up_shift_x" value="0.065"/>
    <xacro:property name="up_shift_y" value="0.03"/>
    <xacro:property name="up_shift_z" value="0.0"/>    
    
    <xacro:property name="mid_leg_aprox_x" value="0.22"/>
    <xacro:property name="mid_leg_aprox_y" value="0.02"/>
    <xacro:property name="mid_leg_aprox_z" value="0.06"/>
    <xacro:property name="mid_leg_mass" value="0.25"/>
    <xacro:property name="mid_shift_x" value="0.07"/>
    <xacro:property name="mid_shift_y" value="0.01"/>
    <xacro:property name="mid_shift_z" value="0.0"/>
    
    <xacro:property name="feet_aprox_x" value="0.25"/>
    <xacro:property name="feet_aprox_y" value="0.06"/>
    <xacro:property name="feet_aprox_z" value="0.025"/>
    <xacro:property name="feet_mass" value="0.25"/>
    <xacro:property name="feet_shift_x" value="0.02"/>
    <xacro:property name="feet_shift_y" value="0.0"/>
    <xacro:property name="feet_shift_z" value="-0.065"/>
    
    <!--
    SERVO TRANS
    -->
    <xacro:macro name="servtransmission" params="joint">
        <transmission name="${joint}_transm">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint}">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="${joint}_motor">
                <hardwareInterface>hardware_interface/PositionActuatorInterface</hardwareInterface>
            </actuator>
        </transmission>
    </xacro:macro>
    
    <xacro:macro name="servtransmission_v" params="joint">
        <transmission name="${joint}_transm">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint}">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${joint}_motor">
                <hardwareInterface>hardware_interface/VelocityActuatorInterface</hardwareInterface>
            </actuator>
        </transmission>
    </xacro:macro>
    
    <!-- 
    FULL LEG
    -->
    <xacro:macro name="bd1_leg" params="side y_mul servo_velocity servo_effort">
        
        <!--
        UP
        -->
        <link name="up_leg_${side}_link">
            <visual>            
                <geometry>
                    <mesh filename="file://$(find bd1_description)/mesh/up_leg_${side}_m.dae"/>                
                    <!--<box size="${up_leg_aprox_x} ${up_leg_aprox_y} ${up_leg_aprox_z}"/>-->
                </geometry>
                <material name="white">
                <color rgba="1 1 1 1"/>
            </material>
            </visual>
            
            <collision>
                <origin xyz="${up_shift_x} ${y_mul*up_shift_y} ${up_shift_z}" rpy=" 0 0 0"/>
                <geometry>                
                    <box size="${up_leg_aprox_x} ${up_leg_aprox_y} ${up_leg_aprox_z}"/>
                </geometry>
            </collision>
            
            <inertial>
                <origin xyz="${up_shift_x} ${y_mul*up_shift_y} ${up_shift_z}" rpy=" 0 0 0"/>
                <mass value="${up_leg_mass}"/>
                <inertia
                    ixx="${0.08*up_leg_mass*(up_leg_aprox_y*up_leg_aprox_y+up_leg_aprox_z*up_leg_aprox_z)}" ixy="0" ixz="0"
                    iyy="${0.08*up_leg_mass*(up_leg_aprox_x*up_leg_aprox_x+up_leg_aprox_z*up_leg_aprox_z)}" iyz="0"
                    izz="${0.08*up_leg_mass*(up_leg_aprox_y*up_leg_aprox_y+up_leg_aprox_x*up_leg_aprox_x)}"
                />
            </inertial>
        </link>

        <joint name="up_leg_${side}_j" type="revolute">
            <parent link="body_link"/>
            <child link="up_leg_${side}_link"/>
            
            <origin xyz="0 ${y_mul*legs_baseline/2} 0" rpy="0 ${pi/2+1.5} 0"/>
            <limit effort="${servo_effort}" velocity="${servo_velocity}" lower="${-pi}0" upper="0"/>
            <axis xyz="0 1 0"/>
        </joint>
        
        <xacro:servtransmission_v joint="up_leg_${side}_j"/>
        
        <!--
        MID
        -->
        <link name="mid_leg_${side}_link">
            <visual>            
                <geometry>
                    <mesh filename="file://$(find bd1_description)/mesh/mid_leg_${side}_m.dae"/>                
                    <!--<box size="${mid_leg_aprox_x} ${mid_leg_aprox_y} ${mid_leg_aprox_z}"/>-->
                </geometry>
                <material name="white">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>
            
            <collision>
                <origin xyz="${mid_shift_x} ${-y_mul*mid_shift_y} ${mid_shift_z}" rpy=" 0 0 0"/>
                <geometry>                
                    <box size="${mid_leg_aprox_x} ${mid_leg_aprox_y} ${mid_leg_aprox_z}"/>
                </geometry>
            </collision>
            
            <inertial>
                <origin xyz="${mid_shift_x} ${-y_mul*mid_shift_y} ${mid_shift_z}" rpy=" 0 0 0"/>
                <mass value="${mid_leg_mass}"/>                
                <inertia
                    ixx="${0.08*mid_leg_mass*(mid_leg_aprox_y*mid_leg_aprox_y+mid_leg_aprox_z*mid_leg_aprox_z)}" ixy="0" ixz="0"
                    iyy="${0.08*mid_leg_mass*(mid_leg_aprox_x*mid_leg_aprox_x+mid_leg_aprox_z*mid_leg_aprox_z)}" iyz="0"
                    izz="${0.08*mid_leg_mass*(mid_leg_aprox_y*mid_leg_aprox_y+mid_leg_aprox_x*mid_leg_aprox_x)}"
                />
            </inertial>
        </link>

        <joint name="mid_leg_${side}_j" type="revolute">
            <parent link="up_leg_${side}_link"/>
            <child link="mid_leg_${side}_link"/>
            
            <origin xyz="0.15 ${y_mul*0.009} 0" rpy="0 -3 0"/>
            <limit effort="${servo_effort}" velocity="${servo_velocity}" lower="0" upper="${pi}"/>
            <axis xyz="0 1 0"/>
        </joint>
        
        <xacro:servtransmission_v joint="mid_leg_${side}_j"/>
        
        <!--
        FEET
        -->
        
        <link name="feet_${side}_link">
            <visual>            
                <geometry>
                    <mesh filename="file://$(find bd1_description)/mesh/feet_m.dae"/>                
                    <!--<box size="${feet_aprox_x} ${feet_aprox_y} ${feet_aprox_z}"/>-->
                </geometry>
                <material name="white">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>
            
            <collision>
                <origin xyz="${feet_shift_x} ${-y_mul*feet_shift_y} ${feet_shift_z}" rpy=" 0 0 0"/>
                <geometry>                
                    <box size="${feet_aprox_x} ${feet_aprox_y} ${feet_aprox_z}"/>
                </geometry>
            </collision>
            
            <inertial>
                <origin xyz="${feet_shift_x} ${-y_mul*feet_shift_y} ${feet_shift_z}" rpy=" 0 0 0"/>
                <mass value="${feet_mass}"/>                
                <inertia
                    ixx="${0.08*feet_mass*(feet_aprox_y*feet_aprox_y+feet_aprox_z*feet_aprox_z)}" ixy="0" ixz="0"
                    iyy="${0.08*feet_mass*(feet_aprox_x*feet_aprox_x+feet_aprox_z*feet_aprox_z)}" iyz="0"
                    izz="${0.08*feet_mass*(feet_aprox_y*feet_aprox_y+feet_aprox_x*feet_aprox_x)}"
                />
            </inertial>
        </link>

        <joint name="feet_${side}_j" type="revolute">
            <parent link="mid_leg_${side}_link"/>
            <child link="feet_${side}_link"/>
            
            <origin xyz="0.15 ${-y_mul*0.0045} 0" rpy="0 0 0"/>
            <limit effort="${servo_effort}" velocity="${servo_velocity}" lower="${-pi}" upper="0"/>
            <axis xyz="0 1 0"/>
        </joint>
        
        <gazebo reference="feet_${side}_link">
            <!--<material>Gazebo/Black</material>-->
            <mu1>2</mu1>
            <mu2>5</mu2>
            <!--<dampingFactor>0.05</dampingFactor>-->
            <kp>20000</kp>
            <kd>1</kd>
        </gazebo>
        
        <xacro:servtransmission_v joint="feet_${side}_j"/>
        
    </xacro:macro>
    
</robot>
    
