<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
            
    <xacro:property name="legs_baseline" value="0.12"/>
    
    <xacro:property name="hip_aprox_x" value="0.24"/>
    <xacro:property name="hip_aprox_y" value="0.04"/>
    <xacro:property name="hip_aprox_z" value="0.12"/>
    <xacro:property name="hip_mass" value="0.25"/>
    <xacro:property name="hip_shift_x" value="0.065"/>
    <xacro:property name="hip_shift_y" value="0.03"/>
    <xacro:property name="hip_shift_z" value="0.0"/>    
    
    <xacro:property name="hip_aprox_x" value="0.22"/>
    <xacro:property name="hip_aprox_y" value="0.02"/>
    <xacro:property name="hip_aprox_z" value="0.06"/>
    <xacro:property name="hip_mass" value="0.25"/>
    <xacro:property name="knee_shift_x" value="0.07"/>
    <xacro:property name="knee_shift_y" value="0.01"/>
    <xacro:property name="knee_shift_z" value="0.0"/>
    
    <xacro:property name="foot_aprox_x" value="0.09"/>
    <xacro:property name="foot_aprox_y" value="0.06"/>
    <xacro:property name="foot_aprox_z" value="0.025"/>
    <xacro:property name="foot_mass" value="0.25"/>
    <xacro:property name="foot_shift_x" value="0.1"/>
    <xacro:property name="foot_shift_y" value="0.0"/>
    <xacro:property name="foot_shift_z" value="-0.065"/>
    
    <xacro:property name="heel_aprox_x" value="0.06"/>
    <xacro:property name="heel_aprox_y" value="0.06"/>
    <xacro:property name="heel_aprox_z" value="0.025"/>
    <xacro:property name="heel_mass" value="0.15"/>
    <xacro:property name="heel_shift_x" value="-0.08"/>
    <xacro:property name="heel_shift_y" value="0.0"/>
    <xacro:property name="heel_shift_z" value="-0.065"/>
    
    <xacro:property name="foot_heel_kp" value="100000"/>
    
    <!--<xacro:property name="servo_friction" value="1000"/>-->
    
    
    <xacro:include filename="$(find bd1_description)/urdf/transmission_$(arg servo_control).xacro"/>
    
    <!-- 
    FULL LEG
    -->
    <xacro:macro name="bd1_leg" params="side y_mul servo_velocity servo_effort">
        
        <!--
        hip
        -->
        <link name="hip_${side}_link">
            <visual>            
                <geometry>
                    <mesh filename="file://$(find bd1_description)/mesh/hip_${side}_m.dae"/>                
                    <!--<box size="${hip_aprox_x} ${hip_aprox_y} ${hip_aprox_z}"/>-->
                </geometry>
                <material name="white">
                <color rgba="1 1 1 1"/>
            </material>
            </visual>
            
            <collision>
                <origin xyz="${hip_shift_x} ${y_mul*hip_shift_y} ${hip_shift_z}" rpy=" 0 0 0"/>
                <geometry>                
                    <box size="${hip_aprox_x} ${hip_aprox_y} ${hip_aprox_z}"/>
                </geometry>
            </collision>
            
            <inertial>
                <origin xyz="${hip_shift_x} ${y_mul*hip_shift_y} ${hip_shift_z}" rpy=" 0 0 0"/>
                <mass value="${hip_mass}"/>
                <inertia
                    ixx="${0.08*hip_mass*(hip_aprox_y*hip_aprox_y+hip_aprox_z*hip_aprox_z)}" ixy="0" ixz="0"
                    iyy="${0.08*hip_mass*(hip_aprox_x*hip_aprox_x+hip_aprox_z*hip_aprox_z)}" iyz="0"
                    izz="${0.08*hip_mass*(hip_aprox_y*hip_aprox_y+hip_aprox_x*hip_aprox_x)}"
                />
            </inertial>
        </link>

        <joint name="hip_${side}_j" type="revolute">
            <parent link="body_link"/>
            <child link="hip_${side}_link"/>
            
            <origin xyz="0 ${y_mul*legs_baseline/2} 0" rpy="0 ${pi/2} 0"/>
            <limit effort="${servo_effort}" velocity="${servo_velocity}" lower="${-pi/2}" upper="0"/>
            <axis xyz="0 -1 0"/>
            <!--<dynamics damping="${servo_friction}"/>-->
        </joint>
        
        <xacro:servtransmission joint="hip_${side}_j"/>
        
        <!--
        knee
        -->
        <link name="knee_${side}_link">
            <visual>            
                <geometry>
                    <mesh filename="file://$(find bd1_description)/mesh/knee_${side}_m.dae"/>                
                    <!--<box size="${hip_aprox_x} ${hip_aprox_y} ${hip_aprox_z}"/>-->
                </geometry>
                <material name="white">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>
            
            <collision>
                <origin xyz="${knee_shift_x} ${-y_mul*knee_shift_y} ${knee_shift_z}" rpy=" 0 0 0"/>
                <geometry>                
                    <box size="${hip_aprox_x} ${hip_aprox_y} ${hip_aprox_z}"/>
                </geometry>
            </collision>
            
            <inertial>
                <origin xyz="${knee_shift_x} ${-y_mul*knee_shift_y} ${knee_shift_z}" rpy=" 0 0 0"/>
                <mass value="${hip_mass}"/>                
                <inertia
                    ixx="${0.08*hip_mass*(hip_aprox_y*hip_aprox_y+hip_aprox_z*hip_aprox_z)}" ixy="0" ixz="0"
                    iyy="${0.08*hip_mass*(hip_aprox_x*hip_aprox_x+hip_aprox_z*hip_aprox_z)}" iyz="0"
                    izz="${0.08*hip_mass*(hip_aprox_y*hip_aprox_y+hip_aprox_x*hip_aprox_x)}"
                />
            </inertial>
        </link>

        <joint name="knee_${side}_j" type="revolute">
            <parent link="hip_${side}_link"/>
            <child link="knee_${side}_link"/>
            
            <origin xyz="0.15 ${y_mul*0.009} 0" rpy="0 0 0"/>
            <limit effort="${servo_effort}" velocity="${servo_velocity}" lower="0" upper="${pi}"/>
            <axis xyz="0 -1 0"/>
            <!--<dynamics damping="${servo_friction}"/>-->
        </joint>
        
        <xacro:servtransmission joint="knee_${side}_j"/>
        
        <!--
        foot
        -->
        
        <link name="foot_${side}_link">
            <visual>            
                <geometry>
                    <mesh filename="file://$(find bd1_description)/mesh/foot_m.dae"/>                
                    <!--<box size="${foot_aprox_x} ${foot_aprox_y} ${foot_aprox_z}"/>-->
                </geometry>
                <material name="white">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>
            
            <collision>
                <origin xyz="${foot_shift_x} ${-y_mul*foot_shift_y} ${foot_shift_z}" rpy=" 0 0 0"/>
                <geometry>                
                    <box size="${foot_aprox_x} ${foot_aprox_y} ${foot_aprox_z}"/>
                </geometry>
            </collision>
            
            <inertial>
                <origin xyz="${foot_shift_x} ${-y_mul*foot_shift_y} ${foot_shift_z}" rpy=" 0 0 0"/>
                <mass value="${foot_mass}"/>                
                <inertia
                    ixx="${0.08*foot_mass*(foot_aprox_y*foot_aprox_y+foot_aprox_z*foot_aprox_z)}" ixy="0" ixz="0"
                    iyy="${0.08*foot_mass*(foot_aprox_x*foot_aprox_x+foot_aprox_z*foot_aprox_z)}" iyz="0"
                    izz="${0.08*foot_mass*(foot_aprox_y*foot_aprox_y+foot_aprox_x*foot_aprox_x)}"
                />
            </inertial>
        </link>

        <joint name="foot_${side}_j" type="revolute">
            <parent link="knee_${side}_link"/>
            <child link="foot_${side}_link"/>
            
            <origin xyz="0.15 ${-y_mul*0.0045} 0" rpy="0 ${-pi/2} 0"/>
            <limit effort="${servo_effort}" velocity="${servo_velocity}" lower="${-pi/2}" upper="${pi/2}"/>
            <axis xyz="0 1 0"/>
            <!--<dynamics damping="${servo_friction}"/>-->
        </joint>
        
        <gazebo reference="foot_${side}_link">
            <!--<material>Gazebo/Black</material>-->
            <mu1>2</mu1>
            <mu2>5</mu2>
            <!--<dampingFactor>0.05</dampingFactor>-->
            <kp>${foot_heel_kp}</kp>
            <kd>1</kd>
        </gazebo>
        
        <xacro:servtransmission joint="foot_${side}_j"/>
        
        <!-- heel -->
        
        <link name="heel_${side}_link">
            <!--<visual>            
                <geometry>                    
                    <box size="${heel_aprox_x} ${heel_aprox_y} ${heel_aprox_z}"/>
                </geometry>
                <material name="white">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>-->
            
            <collision>
                <origin xyz="${heel_shift_x} ${-y_mul*heel_shift_y} ${heel_shift_z}" rpy=" 0 0 0"/>
                <geometry>                
                    <box size="${heel_aprox_x} ${heel_aprox_y} ${heel_aprox_z}"/>
                </geometry>
            </collision>
            
            <inertial>
                <origin xyz="${heel_shift_x} ${-y_mul*heel_shift_y} ${heel_shift_z}" rpy=" 0 0 0"/>
                <mass value="${heel_mass}"/>                
                <inertia
                    ixx="${0.08*heel_mass*(heel_aprox_y*heel_aprox_y+heel_aprox_z*heel_aprox_z)}" ixy="0" ixz="0"
                    iyy="${0.08*heel_mass*(heel_aprox_x*heel_aprox_x+heel_aprox_z*heel_aprox_z)}" iyz="0"
                    izz="${0.08*heel_mass*(heel_aprox_y*heel_aprox_y+heel_aprox_x*heel_aprox_x)}"
                />
            </inertial>
        </link>
        
        <joint name="heel_${side}_j" type="fixed">
            <parent link="foot_${side}_link"/>
            <child link="heel_${side}_link"/>
            
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <!--<limit effort="${servo_effort}" velocity="${servo_velocity}" lower="${-pi}" hipper="0"/>-->
            <!--<axis xyz="0 1 0"/>-->
            <!--<dynamics damping="${servo_friction}"/>-->
        </joint>
        
        <gazebo reference="heel_${side}_link">            
            <mu1>2</mu1>
            <mu2>5</mu2>            
            <kp>${foot_heel_kp}</kp>
            <kd>1</kd>
        </gazebo>
        
    </xacro:macro>
    
</robot>
    
